name: CI - Backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Show variable (allowed)
        run: echo "APP_ENV=${{ vars.APP_ENV }}"

      - name: Show secret (masked)
        run: echo "DUMMY_SECRET=${{ secrets.DUMMY_SECRET }}"

      - name: Run unit tests
        run: npm test
      
      - name: Create test artifact
        run: |
          mkdir -p test-results
          echo "Unit tests OK - $(date)" > test-results/unit.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: backend/test-results/
          retention-days: 5
  
  unit-frontend:
    name: Unit tests (frontend)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci
      - run: npm test -- --watchAll=false

  integration-tests:
    name: Integration tests (API <-> Mongo)
    runs-on: ubuntu-latest
    needs: unit-tests
    defaults:
      run:
        working-directory: backend

    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017

    env:
      MONGO_URI: mongodb://127.0.0.1:27017/test_ci

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Wait for MongoDB
        run: |
          for i in {1..30}; do
            (echo > /dev/tcp/127.0.0.1/27017) >/dev/null 2>&1 && echo "MongoDB is up" && exit 0
            echo "Waiting for MongoDB... ($i/30)"
            sleep 1
          done
          echo "MongoDB did not start in time" && exit 1

      - name: Run integration tests
        run: npm run test:integration

  self-hosted-proof:
    if: github.event_name == 'push'
    name: Proof job on self-hosted runner
    runs-on: self-hosted
    needs: unit-tests
    steps:
      - run: echo "Runner name is $env:RUNNER_NAME"
        shell: powershell


  analyze-artifact:
    name: Reuse artifact
    runs-on: ubuntu-latest
    needs: [unit-tests]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: test-results
          path: downloaded

      - name: Read artifact content
        run: cat downloaded/unit.txt
  
  build-frontend:
    name: Build frontend (dev/staging/prod)
    runs-on: ubuntu-latest
    needs: [unit-frontend]
    strategy:
      matrix:
        envname: [dev, staging, prod]

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - run: npm ci

      - name: Configure env
        run: |
          if [ "${{ matrix.envname }}" = "dev" ]; then
            echo "REACT_APP_API_URL=http://localhost:5000/api" > .env
          elif [ "${{ matrix.envname }}" = "staging" ]; then
            echo "REACT_APP_API_URL=https://staging.example/api" > .env
          else
            echo "REACT_APP_API_URL=https://prod.example/api" > .env
          fi

          echo "APP_ENV=${{ matrix.envname }}" >> .env

          echo "===== ENV FILE ====="
          cat .env

      - name: Build
        run: npm run build

      # fichier preuve
      - name: Create build info file
        run: |
          echo "env=${{ matrix.envname }}" > build/build-info.txt
          echo "api_url=$(grep REACT_APP_API_URL .env | cut -d= -f2)" >> build/build-info.txt
          echo "commit=${GITHUB_SHA}" >> build/build-info.txt
          echo "date=$(date -u)" >> build/build-info.txt
          echo "===== BUILD INFO ====="
          cat build/build-info.txt

      # zip du build
      - name: Zip build folder
        run: |
          cd build
          zip -r ../frontend-build-${{ matrix.envname }}.zip .
          cd ..
          ls -lh frontend-build-${{ matrix.envname }}.zip

      # upload du zip comme artefact (téléchargeable)
      - uses: actions/upload-artifact@v4
        with:
          name: frontend-build-${{ matrix.envname }}
          path: frontend/frontend-build-${{ matrix.envname }}.zip
          retention-days: 5
  docker-image-frontend:
    name: Docker image frontend (.tar artifact)
    runs-on: ubuntu-latest
    needs: [unit-frontend]
    strategy:
      matrix:
        envname: [dev, staging, prod]

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            -f docker/frontend/Dockerfile.prod \
            -t tp-frontend:${{ matrix.envname }} \
            .

      - name: Save image as tar
        run: |
          docker save tp-frontend:${{ matrix.envname }} -o tp-frontend-${{ matrix.envname }}.tar
          ls -lh tp-frontend-${{ matrix.envname }}.tar

      - name: Upload tar artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-frontend-${{ matrix.envname }}
          path: tp-frontend-${{ matrix.envname }}.tar
          retention-days: 5


